site_name: Pexels Android
repo_url: https://github.com/SanjayDevTech/pexels-android
repo_name: SanjayDevTech/pexels-android

nav:
  - Overview: index.md
  - Getting Started:
    - Setup: getting-started/index.md
    - Core: getting-started/core.md
    - Paging 3: getting-started/paging3.md
  - Guide: guide.md
  - Changelog: changelog.md

theme:
  name: material
  icon:
    logo: material/view-gallery-outline
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  highlightjs: true
  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant

plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true

extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/SanjayDevTech

    - icon: fontawesome/brands/github 
      link: https://github.com/SanjayDevTech

    - icon: fontawesome/brands/linkedin 
      link: https://linkedin.com/in/sanjaydevtech

    - icon: fontawesome/brands/medium 
      link: https://sanjaydevtech.medium.com

  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

