name: main_push_ci

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Ktlint check for code conventions
        run: ./gradlew ktlintCheck

      - name: Run unit test in debug build
        id: testDebug
        run: ./gradlew testDebugUnitTest

      - name: Assemble to debug
        run: ./gradlew assembleDebug

      - run: pip install mkdocs mkdocs-material mkdocs-material-extensions pymdown-extensions mkdocs-minify-plugin 
      - run: mkdocs gh-deploy --force